---
micronaut:
  application:
    name: catalog-api
  router:
        static-resources:
            swagger:
                paths:
                  - classpath:META-INF/swagger
                  - classpath:swagger
                mapping: /swagger/**
  io:
    watch:
      paths: src/main
      restart: true

---
kafka:
  bootstrap:
    servers: localhost:9092
