---
micronaut:
  application:
    name: catalog-api
  router:
    static-resources:
        swagger-ui:
          paths:
            - classpath:swagger-ui
          mapping: /swagger-ui/**
        swagger:
          paths:
            - classpath:META-INF/swagger
          mapping: /swagger/**
  io:
    watch:
      paths: src/main
      restart: true
---
kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    'capi-item-producer':
      key:
        serializer: org.apache.kafka.common.serialization.StringSerializer
      value:
        serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: -1
      max:
        block:
          ms: 30000
      transaction:
        timeout:
          ms: 30000
      schema:
        registry:
          url: http://localhost:8081