{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "catalog-api.serviceAccountName" . }}
  labels:
{{ include "catalog-api.labels" . | indent 4 }}
{{- end -}}
